
name: Java CI with Gradle

on:
  push:
    branches: 
      - '*'
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - '*'
    paths:
      - 'backend/**'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - run: gradle init
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2 
      with:
        gradle-version: 8.2.1
        arguments: build
        
